In [172]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.compose import ColumnTransformer 
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
import statsmodels.api as sm

import statsmodels.formula.api as smf


In [173]:
data  = pd.read_csv('Startups_company.csv')
data.head(10)

R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94
5  131876.90        99814.71        362861.36    New York  156991.12
6  134615.46       147198.87        127716.82  California  156122.51
7  130298.13       145530.06        323876.68     Florida  155752.60
8  120542.52       148718.95        311613.29    New York  152211.77
9  123334.88       108679.17        304981.62  California  149759.96

In [175]:
real_x = data.iloc[:,0:4].values
real_y = data.iloc[:,4].values

In [176]:
le = LabelEncoder()
real_x[:,3] = le.fit_transform(real_x[:,3])
oneHE = ColumnTransformer([("State", OneHotEncoder(), [3])], remainder = 'passthrough')
real_x = oneHE.fit_transform(real_x)                   

In [177]:
real_x = real_x[:,1:]

In [178]:
training_x,test_x, training_y,test_y = train_test_split(real_x,real_y,test_size=0.2,random_state=0)


In [179]:
MLR = LinearRegression()
MLR.fit(training_x,training_y)

LinearRegression()

In [180]:
pred_y = MLR.predict(test_x)
pred_y


array([103015.20159796, 132582.27760816, 132447.73845175,  71976.09851259,
       178537.48221054, 116161.24230163,  67851.69209676,  98791.73374688,
       113969.43533012, 167921.0656955 ])

In [181]:
test_y

array([103282.38, 144259.4 , 146121.95,  77798.83, 191050.39, 105008.31,
        81229.06,  97483.56, 110352.25, 166187.94])

In [182]:
MLR.coef_

array([-9.59284160e+02,  6.99369053e+02,  7.73467193e-01,  3.28845975e-02,
        3.66100259e-02])

In [183]:
MLR.intercept_

42554.16761776614

In [184]:
#y = b0 + b1x1 + b2x2----------+bnxn
real_x = np.append(arr=np.ones((50,1),dtype=np.int),values=real_x,axis=1)

#X = np.append(arr=np.ones((50,1),dtype=np.int), values = X,axis = 1)


In [185]:
x_opt = real_x[:,[0,1,2,3,4,5]]

In [199]:
reg_OLS = smf.ols(endog=real_y,exog=x_opt)


TypeError: from_formula() missing 2 required positional arguments: 'formula' and 'data'

In [197]:
reg_OLS.summary()

NameError: name 'reg_OLS' is not defined

ERROR! Session/line number was not unique in database. History logging moved to new session 102
